// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, key_hash, key_prefix, name)
VALUES ($1, $2, $3, $4)
RETURNING
    id,
    user_id,
    key_hash,
    key_prefix,
    name,
    created_at,
    revoked_at
`

type CreateAPIKeyParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	KeyHash   string      `json:"key_hash"`
	KeyPrefix string      `json:"key_prefix"`
	Name      string      `json:"name"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Name,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Name,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT
    id,
    user_id,
    key_prefix
FROM api_keys
WHERE key_hash = $1
  AND revoked_at IS NULL
`

type GetAPIKeyByHashRow struct {
	ID        pgtype.UUID `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	KeyPrefix string      `json:"key_prefix"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(&i.ID, &i.UserID, &i.KeyPrefix)
	return i, err
}
