// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT
    id,
    user_id,
    key_prefix
FROM api_keys
WHERE key_hash = $1
  AND revoked_at IS NULL
`

type GetAPIKeyByHashRow struct {
	ID        pgtype.UUID `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	KeyPrefix string      `json:"key_prefix"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(&i.ID, &i.UserID, &i.KeyPrefix)
	return i, err
}
