// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	KeyHash   string             `json:"key_hash"`
	KeyPrefix string             `json:"key_prefix"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Username      *string            `json:"username"`
	ClerkUserID   *string            `json:"clerk_user_id"`
	WallbitUserID *string            `json:"wallbit_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Workflow struct {
	ID              pgtype.UUID        `json:"id"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	Slug            string             `json:"slug"`
	DisplayName     string             `json:"display_name"`
	Description     string             `json:"description"`
	LatestVersionID pgtype.UUID        `json:"latest_version_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type WorkflowVersion struct {
	ID            pgtype.UUID        `json:"id"`
	WorkflowID    pgtype.UUID        `json:"workflow_id"`
	Version       string             `json:"version"`
	Content       string             `json:"content"`
	ContentSha256 string             `json:"content_sha256"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
