// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (author_id, slug, display_name, description)
VALUES ($1, $2, $3, $4)
RETURNING
    id,
    author_id,
    slug,
    display_name,
    description,
    latest_version_id,
    created_at
`

type CreateWorkflowParams struct {
	AuthorID    pgtype.UUID `json:"author_id"`
	Slug        string      `json:"slug"`
	DisplayName string      `json:"display_name"`
	Description string      `json:"description"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.AuthorID,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.LatestVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkflowByAuthorAndSlug = `-- name: GetWorkflowByAuthorAndSlug :one
SELECT
    w.id,
    w.author_id,
    w.slug,
    w.display_name,
    w.description,
    w.latest_version_id,
    w.created_at
FROM workflows w
INNER JOIN users u ON u.id = w.author_id
WHERE u.username = $1
  AND w.slug = $2
`

type GetWorkflowByAuthorAndSlugParams struct {
	Username *string `json:"username"`
	Slug     string  `json:"slug"`
}

func (q *Queries) GetWorkflowByAuthorAndSlug(ctx context.Context, arg GetWorkflowByAuthorAndSlugParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByAuthorAndSlug, arg.Username, arg.Slug)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.LatestVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkflowByAuthorIDAndSlug = `-- name: GetWorkflowByAuthorIDAndSlug :one
SELECT
    id,
    author_id,
    slug,
    display_name,
    description,
    latest_version_id,
    created_at
FROM workflows
WHERE author_id = $1
  AND slug = $2
`

type GetWorkflowByAuthorIDAndSlugParams struct {
	AuthorID pgtype.UUID `json:"author_id"`
	Slug     string      `json:"slug"`
}

func (q *Queries) GetWorkflowByAuthorIDAndSlug(ctx context.Context, arg GetWorkflowByAuthorIDAndSlugParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByAuthorIDAndSlug, arg.AuthorID, arg.Slug)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.LatestVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkflowMetadataByAuthorAndSlug = `-- name: GetWorkflowMetadataByAuthorAndSlug :one
SELECT
    w.slug,
    w.display_name,
    w.description,
    w.created_at AS workflow_created_at,
    wv.version,
    wv.content_sha256,
    wv.created_at AS published_at
FROM workflows w
INNER JOIN users u ON u.id = w.author_id
INNER JOIN workflow_versions wv ON wv.id = w.latest_version_id
WHERE u.username = $1
  AND w.slug = $2
`

type GetWorkflowMetadataByAuthorAndSlugParams struct {
	Username *string `json:"username"`
	Slug     string  `json:"slug"`
}

type GetWorkflowMetadataByAuthorAndSlugRow struct {
	Slug              string             `json:"slug"`
	DisplayName       string             `json:"display_name"`
	Description       string             `json:"description"`
	WorkflowCreatedAt pgtype.Timestamptz `json:"workflow_created_at"`
	Version           string             `json:"version"`
	ContentSha256     string             `json:"content_sha256"`
	PublishedAt       pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) GetWorkflowMetadataByAuthorAndSlug(ctx context.Context, arg GetWorkflowMetadataByAuthorAndSlugParams) (GetWorkflowMetadataByAuthorAndSlugRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowMetadataByAuthorAndSlug, arg.Username, arg.Slug)
	var i GetWorkflowMetadataByAuthorAndSlugRow
	err := row.Scan(
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.WorkflowCreatedAt,
		&i.Version,
		&i.ContentSha256,
		&i.PublishedAt,
	)
	return i, err
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT
    u.username,
    w.slug,
    w.display_name,
    w.description,
    wv.version,
    wv.created_at AS published_at
FROM workflows w
INNER JOIN users u ON u.id = w.author_id
INNER JOIN workflow_versions wv ON wv.id = w.latest_version_id
WHERE w.latest_version_id IS NOT NULL
ORDER BY wv.created_at DESC
LIMIT $1 OFFSET $2
`

type ListWorkflowsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListWorkflowsRow struct {
	Username    *string            `json:"username"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Description string             `json:"description"`
	Version     string             `json:"version"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]ListWorkflowsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflows, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowsRow{}
	for rows.Next() {
		var i ListWorkflowsRow
		if err := rows.Scan(
			&i.Username,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.Version,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowLatestVersion = `-- name: UpdateWorkflowLatestVersion :one
UPDATE workflows w
SET latest_version_id = $2
WHERE w.id = $1
  AND EXISTS (
      SELECT 1
      FROM workflow_versions wv
      WHERE wv.id = $2
        AND wv.workflow_id = w.id
  )
RETURNING
    w.id,
    w.author_id,
    w.slug,
    w.display_name,
    w.description,
    w.latest_version_id,
    w.created_at
`

type UpdateWorkflowLatestVersionParams struct {
	ID              pgtype.UUID `json:"id"`
	LatestVersionID pgtype.UUID `json:"latest_version_id"`
}

func (q *Queries) UpdateWorkflowLatestVersion(ctx context.Context, arg UpdateWorkflowLatestVersionParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflowLatestVersion, arg.ID, arg.LatestVersionID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.LatestVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorkflowOnPublish = `-- name: UpdateWorkflowOnPublish :exec
UPDATE workflows
SET
    display_name = $2,
    description = $3
WHERE id = $1
`

type UpdateWorkflowOnPublishParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	Description string      `json:"description"`
}

func (q *Queries) UpdateWorkflowOnPublish(ctx context.Context, arg UpdateWorkflowOnPublishParams) error {
	_, err := q.db.Exec(ctx, updateWorkflowOnPublish, arg.ID, arg.DisplayName, arg.Description)
	return err
}
