// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package store

import (
	"context"
)

const getWorkflowByAuthorAndSlug = `-- name: GetWorkflowByAuthorAndSlug :one
SELECT w.id, w.author_id, w.slug, w.display_name, w.description, w.latest_version_id, w.created_at
FROM workflows w
INNER JOIN users u ON u.id = w.author_id
WHERE u.username = $1
AND w.slug = $2
`

type GetWorkflowByAuthorAndSlugParams struct {
	Username *string `json:"username"`
	Slug     string  `json:"slug"`
}

func (q *Queries) GetWorkflowByAuthorAndSlug(ctx context.Context, arg GetWorkflowByAuthorAndSlugParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByAuthorAndSlug, arg.Username, arg.Slug)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.LatestVersionID,
		&i.CreatedAt,
	)
	return i, err
}
