// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_versions.sql

package store

import (
	"context"
)

const getLatestWorkflowVersionBySlug = `-- name: GetLatestWorkflowVersionBySlug :one
SELECT wv.id, wv.workflow_id, wv.version, wv.content, wv.content_sha256, wv.created_at
FROM workflow_versions wv
INNER JOIN workflows w ON w.id = wv.workflow_id
INNER JOIN users u ON u.id = w.author_id
WHERE u.username = $1
  AND w.slug = $2
  AND wv.id = w.latest_version_id
`

type GetLatestWorkflowVersionBySlugParams struct {
	Username *string `json:"username"`
	Slug     string  `json:"slug"`
}

func (q *Queries) GetLatestWorkflowVersionBySlug(ctx context.Context, arg GetLatestWorkflowVersionBySlugParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowVersionBySlug, arg.Username, arg.Slug)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Version,
		&i.Content,
		&i.ContentSha256,
		&i.CreatedAt,
	)
	return i, err
}
